
#ifndef special_keys_cpp
#define special_keys_cpp

enum special_keys {
    KEY_SPACE = 32,
    KEY_DEL = 127,
    KEY_MENU = 9,
    KEY_RETURN = 10,
    LEFT = -1,
    RIGHT = 1,
    UP = -1,
    DOWN = 1,
    ARROW_UP = 259,
    ARROW_DOWN = 258,
    ARROW_LEFT = 260,
    ARROW_RIGHT = 261,
    KEY_a = 97,
    KEY_d = 100,
    KEY_1 = 49,
    KEY_2 = 50,
    KEY_3 = 51,
    KEY_4 = 52,
    KEY_5 = 53,
    KEY_6 = 54,
    KEY_7 = 55,
    KEY_8 = 56,
    KEY_9 = 57,
    KEY_0 = 48,
    KEY_q = 113,
    KEY_s = 115,
    KEY_r = 114,
    KEY_n = 110,
    KEY_b = 98,
    KEY_c = 99,
    KEY_e = 101,
    KEY_f = 102,
    KEY_g = 103,
    KEY_h = 104,
    KEY_i = 105,
    KEY_j = 106,
    KEY_k = 107,
    KEY_l = 108,
    KEY_m = 109,
    KEY_o = 111,
    KEY_p = 112,
    KEY_t = 116,
    KEY_u = 117,
    KEY_v = 118,
    KEY_w = 119,
    KEY_x = 120,
    KEY_y = 121,
    KEY_z = 122,
    KEY_A = 65,
    KEY_B = 66,
    KEY_C = 67,
    KEY_D = 68,
    KEY_E = 69,
    KEY_F = 70,
    KEY_G = 71,
    KEY_H = 72,
    KEY_I = 73,
    KEY_J = 74,
    KEY_K = 75,
    KEY_L = 76,
    KEY_M = 77,
    KEY_N = 78,
    KEY_O = 79,
    KEY_P = 80,
    KEY_Q = 81,
    KEY_R = 82,
    KEY_S = 83,
    KEY_T = 84,
    KEY_U = 85,
    KEY_V = 86,
    KEY_W = 87,
    KEY_X = 88,
    KEY_Y = 89,
    KEY_Z = 90,
    KEY_EXCLAMATION = 33,
    KEY_QUOTATION = 34,
    KEY_POUND = 35,
    KEY_DOLLAR = 36,
    KEY_PERCENT = 37,
    KEY_AMP = 38,
    KEY_quotation = 39,
    KEY_BRACKET_L = 40,
    KEY_BRACKET_R = 41,
    KEY_ASTERISK = 42,
    KEY_PLUS = 43,
    KEY_COMMA = 44,
    KEY_DASH = 45,
    KEY_PERIOD = 46,
    KEY_SLASH = 47,
    KEY_COLON = 58,
    KEY_SEMICOLON = 59,
    KEY_LESS = 60,
    KEY_EQUAL = 61,
    KEY_GREAT = 62,
    KEY_QUESTION = 63,
    KEY_AT = 64,
    KEY_BOX_BRACKET_L = 91,
    KEY_BOX_BRACKET_R = 93,
    KEY_CARET = 94,
    KEY_UNDERSCORE = 95,
    KEY_CUR_BRACKET_L = 123,
    KEY_CUR_BRACKET_R = 125,
    KEY_RESIZE = 410,
    KEY_NULL = 0
};

// map<int, string> keyboard_upper = {
//    {KEY_EXCLAMATION, "!"}, {KEY_AT, "@"}, {KEY_POUND, "#"}, {KEY_DOLLAR,
//    "$"}, {KEY_PERCENT, "%"}, {KEY_CARET, "^"},{KEY_AMP, "&"}, {KEY_ASTERISK,
//    "*"}, {KEY_BRACKET_L, "("}, {KEY_BRACKET_R, ")"}, {KEY_UNDERSCORE, "_"},
//    {KEY_PLUS, "+"}, {KEY_DEL, "DEL"},
//
//    {KEY_Q, "q"}, {KEY_W, "w"}, {KEY_E, "e"}, {KEY_R, "r"}, {KEY_T, "t"},
//    {KEY_Y, "y"}, {KEY_U, "u"}, {KEY_I, "i"}, {KEY_O, "o"}, {KEY_P, "p"},
//    {KEY_CUR_BRACKET_L, "["}, {KEY_CUR_BRACKET_R, "]"},
//
//    {KEY_A, "a"}, {KEY_S, "s"}, {KEY_D, "d"}, {KEY_F, "f"}, {KEY_G, "g"},
//    {KEY_H, "h"}, {KEY_J, "j"}, {KEY_K, "k"}, {KEY_L, "l"},
//    {KEY_COLON, ";"}, {KEY_QUOTATION, "'"},
//
//    {KEY_Z, "z"}, {KEY_X, "x"}, {KEY_C, "c"}, {KEY_V, "v"}, {KEY_B, "b"},
//    {KEY_N, "n"}, {KEY_M, "m"}, {KEY_LESS, ","}, {KEY_GREAT, "."},
//    {KEY_QUESTION, "/"}, {KEY_SPACE, "SPACE"}
//};

#endif
